import Navbar from "@/pages/rootapp/Navbar"
import "../globals.css"
import Footer from "@/pages/rootapp/Footer"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <div className="Gradient">
      <Navbar/>
        {children}
        <Footer/>
        </div>
    </>
  )
}
